// export const TH = [
//   "NIK",
//   "Name",
//   "Gender",
//   "Bank Card No.",
//   "Bank Account No.",
//   "Family Card No.",
//   "Marriage Status",
//   "Mother Name",
//   "Place of birth",
//   "Date of birth",
//   "Home Address",
//   "National Card ID No.",
//   "Date Start",
//   "First Contract",
//   "Second Contract",
//   "End Contract ",
//   "Department",
//   "Employee Type",
//   "Salary Rp.",
//   "Position",
//   "O/T Paid",
//   "Meal paid",
//   "Meal Rp.",
//   "Grading",
// ];
export const TH = [
  "NIK",
  "Gender",
  "Name",
  "Card number",
  "Account Number",
  "Family Card No.",
  "Marriage Status",
  "Mother Name",
  "Place and Date Birth",
  "Home Address",
  "National ID Card No.",
  "Date Start",
  "First",
  "Second",
  "End",
  "Department",
  "Employee Type",
  "Basic Salary",
  "Position",
  "O/T paid",
  "Meal allowance",
  "Grading",
];

// 22

// NIK: "NIK",
//   Name: "Name",
//   Gender: "Gender",
//   BankCard: "Bank Card No.",
//   BankAccount: "Bank Account No.",
//   FamilyCard: "Family Card No.",
//   Marriage: "Marriage Status",
//   Mother: "Mother Name",
//   PlaceOfBirth: "Place of birth",
//   Birth: "Date of birth",
//   Home: "Home Address",
//   NationalCard: "National Card ID No.",
//   DateStart: "Date Start",
//   FirstC: "First Contract",
//   SecondC: "Second Contract",
//   EndC: "End Contract ",
//   Department: "Department",
//   Employee: "Employee Type",
//   Salary: "Salary Rp.",
//   Position: "Position",
//   OT: "O/T Paid",
//   MealPaid: "Meal paid",
//   MealRp: "Meal Rp.",
//   Grading: "Grading",
