export const TH = [
  "NIK",
  "Gender",
  "Name",
  "Bank Card No",
  "Bank Account No",
  "Family Card No.",
  "Marriage Status",
  "Mother Name",
  "Place and Date Birth",
  "Home Address",
  "National ID Card No.",
  "Date Start",
  "First",
  "Second",
  "End",
  "Department",
  "Employee Type",
  "Basic Salary",
  "Position",
  "O/T paid",
  "Meal allowance",
  "Grading",
];

export const DATAS = [
  "name",
  "card_number",
  "bank_account_no",
  "family_card_number",
  "marriage_code",
  "mother_name",
  "dob",
  "home_address_1",
  "home_address_2",
  "nc_id",
  "contract_start_date",
  "contract_first",
  "contract_second",
  "contract_end",
  "department_name",
  "type",
  "basic_salary",
  "position_name",
  "entitle_ot",
  "meal_allowance_paid",
  "grade_name",
];
