export const OPTIONSGRADE = [
  { id: 8, value: "Tabitha Kutch PhD", label: "Tabitha Kutch PhD" },
  { id: 6, value: "Melissa Johnson", label: "Melissa Johnson" },
  { id: 1, value: "Danial Stoltenberg", label: "Danial Stoltenberg" },
];

export const OPTIONSBENEFIT = [
  { value: "Cameron Brown", label: "Cameron Brown" },
  { value: "Mr. Arthur Aufderhar", label: "Mr. Arthur Aufderhar" },
  { value: "Mr. Brown Herzog IV", label: "Mr. Brown Herzog IV" },
  { value: "Nicolas Wilderman", label: "Nicolas Wilderman" },
  { value: "Aylin Langosh", label: "Aylin Langosh" },
  { value: "Pinkie Ortiz PhD", label: "Pinkie Ortiz PhD" },
  { value: "Ms. Evangeline Halvorson", label: "Ms. Evangeline Halvorson" },
  { value: "Beryl Purdy", label: "Beryl Purdy" },
  { value: "Melany Wintheiser", label: "Melany Wintheiser" },
  { value: "Geoffrey McGlynn", label: "Geoffrey McGlynn" },
  { value: "Miss Savanna Cole", label: "Miss Savanna Cole" },
  { value: "Rhiannon Kihn V", label: "Rhiannon Kihn V" },
  { value: "Prof. Trever Larkin I", label: "Prof. Trever Larkin I" },
  { value: "Esta Jast", label: "Esta Jast" },
  { value: "Quincy Gaylord", label: "Quincy Gaylord" },
  { value: "Dr. Vidal Bartoletti", label: "Dr. Vidal Bartoletti" },
  { value: "Twila Hermiston", label: "Twila Hermiston" },
  { value: "Damion Parisian", label: "Damion Parisian" },
  { value: "Izabella Kreiger", label: "Izabella Kreiger" },
  { value: "Adalberto Cruickshank PhD", label: "Adalberto Cruickshank PhD" },
  { value: "Marvin Monahan", label: "Marvin Monahan" },
  { value: "Estella Stamm", label: "Estella Stamm" },
  { value: "Juston Wilderman", label: "Juston Wilderman" },
  { value: "Miss Felicita Mraz", label: "Miss Felicita Mraz" },
  { value: "Madie Fahey", label: "Madie Fahey" },
  { value: "Jessyca bayer MD", label: "essyca bayer MD" },
  { value: "Macy Pagac", label: "Macy Pagac" },
  { value: "Prof. Lyla Bradtke", label: "Prof. Lyla Bradtke" },
  { value: "Zoie Schmidt", label: "Zoie Schmidt" },
  { value: "Orie Kulas Jr.", label: "Orie Kulas Jr." },
  { value: "Lemuel Becker", label: "Lemuel Becker" },
  { value: "Earlene Grady", label: "Earlene Grady" },
  { value: "Boyd Mueller Sr.", label: "Boyd Mueller Sr." },
  {
    value: "Mr. Christopher bartoletti III",
    label: "Mr. Christopher bartoletti III",
  },
  { value: "Juliana Rogahn", label: "Juliana Rogahn" },
  { value: "Oleta Rosenbaum", label: "Oleta Rosenbaum" },
  { value: "Murphy Hodkiewicz", label: "Murphy Hodkiewicz" },
  { value: "Douglas Herman DVM", label: "Douglas Herman DVM" },
  { value: "Gail Bode", label: "Gail Bode" },
  { value: "Mrs. Dasia Bradtke", label: "Mrs. Dasia Bradtke" },
  { value: "Prof. Katarina Skiles", label: "Prof. Katarina Skiles" },
  { value: "Grace Zboncak DDS", label: "Grace Zboncak DDS" },
  { value: "Prof. Kylee Barton", label: "Prof. Kylee Barton" },
  { value: "Loren Greenfelder IV", label: "Loren Greenfelder IV" },
  { value: "Zack Dibbert", label: "Zack Dibbert" },
  { value: "Torrey Bartell", label: "Torrey Bartell" },
  { value: "Everardo Dicki", label: "Everardo Dicki" },
  { value: "Calista Mante", label: "Calista Mante" },
  { value: "Bruce Lynch", label: "Bruce Lynch" },
  { value: "Christelle HerZog PhD", label: "Christelle HerZog PhD" },
  { value: "Adelle Weimann III", label: "Adelle Weimann III" },
  { value: "Angela Metz", label: "Angela Metz" },
  { value: "Brandon Lemke", label: "Brandon Lemke" },
  { value: "Mr. Felton Price", label: "Mr. Felton Price" },
  { value: "Mr. Bruce Farrell", label: "Mr. Bruce Farrell" },
  { value: "River Legros", label: "River Legros" },
  { value: "Jakayla Schimmel", label: "Jakayla Schimmel" },
  { value: "Bayby Marvin", label: "Bayby Marvin" },
  { value: "Marcelina Ward", label: "Marcelina Ward" },
  { value: "Dr. Ide;; Rice", label: "Dr. Ide;; Rice" },
  { value: "Mr. toy Quitzon", label: "Mr. toy Quitzon" },
  { value: "Jaclyn Hahn DVM", label: "Jaclyn Hahn DVM" },
  { value: "Dasia Walsh", label: "Dasia Walsh" },
  { value: "Miss Abigayle DuBuque", label: "Miss Abigayle DuBuque" },
  { value: "Bernard Kuhn", label: "Bernard Kuhn" },
  { value: "Dr. Earnest Marks IV", label: "Dr. Earnest Marks IV" },
  { value: "Mrs. Adaline Powlowski MD", label: "Mrs. Adaline Powlowski MD" },
  { value: "Brent Keebler I", label: "Brent Keebler I" },
];
